"""migration3

Revision ID: 3ab4328ab782
Revises: 915a5e011c4d
Create Date: 2019-04-24 19:30:29.315251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab4328ab782'
down_revision = '915a5e011c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'title')
    # ### end Alembic commands ###
