"""migration2

Revision ID: 915a5e011c4d
Revises: df3ce177db8f
Create Date: 2019-04-24 19:27:22.507434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915a5e011c4d'
down_revision = 'df3ce177db8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films')
    # ### end Alembic commands ###
